sudo: false
language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "nightly"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.5
      - postgresql-10-postgis-2.5-scripts

before_script:
  - psql -U postgres -c "create extension postgis"

install:
  - pip install pytest-cov -r requirements.txt

script:
  - pytest --cov=.

after_success: codecov
