services:
  postgis:
    image: "postgis/postgis:17-3.5-alpine"
    environment:
      POSTGRES_USER: munigeo
      POSTGRES_PASSWORD: munigeo
      POSTGRES_DB: munigeo
    ports:
      - "127.0.0.1:5433:5432"
