"""
Test the data migration that moves translated names from parler
translation tables to direct model fields and back.

Uses a JSON fixture dumped from a real parler-era database (generated by
running the Finland and Helsinki importers at commit 0cad137).
"""

import json
from pathlib import Path

import pytest
from django.contrib.gis.geos import MultiPolygon, Polygon

FIXTURES_DIR = Path(__file__).parent / "fixtures"

# Last parler-era migration
PARLER_STATE = ("munigeo", "0005_update_translation_foreign_keys")


# Expected translation data (subset) to verify correctness
EXPECTED_DIVISION_NAMES = {
    # origin_id -> (name_fi, name_sv)
    "91": ("Helsinki", "Helsingfors"),
    "49": ("Espoo", "Esbo"),
}

EXPECTED_MUNICIPALITY_NAMES = {
    # pk -> (name_fi, name_sv)
    "helsinki": ("Helsinki", "Helsingfors"),
    "espoo": ("Espoo", "Esbo"),
}


def _fixture_sort_key(obj):
    """Sort fixture objects so FK dependencies are satisfied.

    Handles the circular FK between AdministrativeDivision and Municipality:
    - Divisions without a municipality FK come first (the muni-level ones)
    - Then municipalities (which reference those divisions)
    - Then divisions with a municipality FK (sub-divisions)
    """
    MODEL_ORDER = {
        "munigeo.administrativedivisiontype": 0,
        "munigeo.administrativedivision": 10,  # refined below
        "munigeo.municipality": 20,
        "munigeo.administrativedivisiongeometry": 30,
        "munigeo.administrativedivisiontranslation": 40,
        "munigeo.municipalitytranslation": 40,
        "munigeo.streettranslation": 40,
    }
    order = MODEL_ORDER.get(obj["model"], 99)

    # Within divisions, those without municipality FK must come before
    # municipalities, and those with municipality FK must come after.
    if obj["model"] == "munigeo.administrativedivision":
        if obj["fields"].get("municipality"):
            order = 25  # after Municipality
        else:
            order = 10  # before Municipality

    return (order, obj.get("pk", 0))


def load_fixture_with_historical_models(apps, fixture_path):
    """Load a Django JSON fixture using historical models from a migration
    state, so that models deleted from the current codebase can still be
    populated.
    """
    with open(fixture_path) as f:
        data = json.load(f)

    data.sort(key=_fixture_sort_key)

    for entry in data:
        app_label, model_name = entry["model"].split(".")
        Model = apps.get_model(app_label, model_name)
        fields = entry["fields"]
        pk = entry.get("pk")

        kwargs = {}
        if pk is not None:
            kwargs["pk"] = pk

        for field_name, value in fields.items():
            field_obj = Model._meta.get_field(field_name)
            if field_obj.is_relation:
                # Store FK as _id to avoid fetching the related object
                kwargs[f"{field_name}_id"] = value
            elif hasattr(field_obj, "srid"):
                # Geometry field - skip, set a dummy value
                dummy = MultiPolygon(
                    Polygon(((0, 0), (0, 1), (1, 1), (1, 0), (0, 0))),
                    srid=field_obj.srid,
                )
                kwargs[field_name] = dummy
            else:
                kwargs[field_name] = value

        Model.objects.create(**kwargs)


@pytest.mark.django_db(transaction=True)
def test_parler_data_migration_forward(migration_executor):
    executor, latest = migration_executor

    # Migrate to the last parler-era state
    state = executor.migrate([PARLER_STATE])
    executor.loader.build_graph()
    apps = state.apps

    # Load fixture using historical models (translation models still exist)
    load_fixture_with_historical_models(apps, FIXTURES_DIR / "parler_test_data.json")

    # Migrate forward through our new migrations
    state = executor.migrate([latest])
    apps = state.apps

    # Verify AdministrativeDivision names were copied
    Division = apps.get_model("munigeo", "AdministrativeDivision")
    for origin_id, (expected_fi, expected_sv) in EXPECTED_DIVISION_NAMES.items():
        div = Division.objects.get(origin_id=origin_id)
        assert div.name_fi == expected_fi, (
            f"Division {origin_id}: expected name_fi={expected_fi!r}, got {div.name_fi!r}"
        )
        assert div.name_sv == expected_sv, (
            f"Division {origin_id}: expected name_sv={expected_sv!r}, got {div.name_sv!r}"
        )

    # Verify Municipality names were copied
    Municipality = apps.get_model("munigeo", "Municipality")
    for pk, (expected_fi, expected_sv) in EXPECTED_MUNICIPALITY_NAMES.items():
        muni = Municipality.objects.get(pk=pk)
        assert muni.name_fi == expected_fi, (
            f"Municipality {pk}: expected name_fi={expected_fi!r}, got {muni.name_fi!r}"
        )
        assert muni.name_sv == expected_sv, (
            f"Municipality {pk}: expected name_sv={expected_sv!r}, got {muni.name_sv!r}"
        )

    # Verify Helsinki division names were also migrated (from Helsinki importer)
    hki_divisions = Division.objects.filter(municipality__pk="helsinki").exclude(
        origin_id="91"
    )
    assert hki_divisions.exists(), "Helsinki sub-divisions should exist"
    # At least some sub-divisions should have names
    named_divisions = [d for d in hki_divisions if d.name_fi is not None]
    assert len(named_divisions) > 0, "Some Helsinki divisions should have name_fi"


@pytest.mark.django_db(transaction=True)
def test_parler_data_migration_backward(migration_executor):
    executor, latest = migration_executor

    # Start at the last parler-era state, load data, migrate forward
    state = executor.migrate([PARLER_STATE])
    executor.loader.build_graph()
    apps = state.apps
    load_fixture_with_historical_models(apps, FIXTURES_DIR / "parler_test_data.json")
    executor.migrate([latest])
    executor.loader.build_graph()

    # Now reverse back to the parler-era state
    state = executor.migrate([PARLER_STATE])
    apps = state.apps

    # Verify translation rows were recreated
    DivisionTranslation = apps.get_model("munigeo", "AdministrativeDivisionTranslation")
    for origin_id, (expected_fi, expected_sv) in EXPECTED_DIVISION_NAMES.items():
        Division = apps.get_model("munigeo", "AdministrativeDivision")
        div = Division.objects.get(origin_id=origin_id)

        fi_trans = DivisionTranslation.objects.get(master_id=div.pk, language_code="fi")
        assert fi_trans.name == expected_fi

        sv_trans = DivisionTranslation.objects.get(master_id=div.pk, language_code="sv")
        assert sv_trans.name == expected_sv

    MuniTranslation = apps.get_model("munigeo", "MunicipalityTranslation")
    for pk, (expected_fi, expected_sv) in EXPECTED_MUNICIPALITY_NAMES.items():
        fi_trans = MuniTranslation.objects.get(master_id=pk, language_code="fi")
        assert fi_trans.name == expected_fi

        sv_trans = MuniTranslation.objects.get(master_id=pk, language_code="sv")
        assert sv_trans.name == expected_sv
