# Generated by Django 3.1.5 on 2021-01-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munigeo', '0004_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
