# Generated by Django 3.0.8 on 2020-08-03 06:26

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ("munigeo", "0004_delete_old_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativedivision",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="administrativedivision",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="administrativedivision",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="administrativedivisiontranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="munigeo.AdministrativeDivision",
            ),
        ),
        migrations.AlterField(
            model_name="municipalitytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="munigeo.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="streettranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="munigeo.Street",
            ),
        ),
    ]
