# Generated by Django 3.2.6 on 2021-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munigeo', '0005_update_administrativedivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativedivision',
            name='extra',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='name_fi',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='name_sv',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
