# Generated by Django 4.2.30 on 2026-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("munigeo", "0008_remove_translation_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativedivision",
            name="name_en",
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="administrativedivision",
            name="name_fi",
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="administrativedivision",
            name="name_sv",
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
