# Generated by Django 4.0 on 2022-03-17 07:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('munigeo', '0009_multilingual_search_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCodeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_fi', models.CharField(blank=True, max_length=100, null=True)),
                ('name_sv', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3067)),
            ],
            options={
                'ordering': ['postal_code'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='munigeo.postalcodearea'),
        ),
    ]
