# Generated by Django 4.2.30 on 2026-05-27 10:38

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


def populate_address_municipality(apps, schema_editor):
    """Populate Address.municipality from Address.street.municipality."""
    Address = apps.get_model("munigeo", "Address")
    Street = apps.get_model("munigeo", "Street")
    Address.objects.update(
        municipality_id=models.Subquery(
            Street.objects.filter(pk=models.OuterRef("street_id")).values(
                "municipality_id"
            )[:1]
        )
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("munigeo", "0009_alter_administrativedivision_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostalCodeArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=5, null=True)),
                ("name_fi", models.CharField(blank=True, max_length=100, null=True)),
                ("name_sv", models.CharField(blank=True, max_length=100, null=True)),
                ("name_en", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "area",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=3067
                    ),
                ),
            ],
            options={
                "ordering": ["postal_code"],
            },
        ),
        migrations.AddField(
            model_name="address",
            name="full_name_en",
            field=models.CharField(
                db_index=True,
                help_text="Full address name. Used for generating search_column",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="full_name_fi",
            field=models.CharField(
                db_index=True,
                help_text="Full address name. Used for generating search_column",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="full_name_sv",
            field=models.CharField(
                db_index=True,
                help_text="Full address name. Used for generating search_column",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="municipality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="munigeo.municipality",
            ),
        ),
        migrations.RunPython(populate_address_municipality, noop),
        migrations.AlterField(
            model_name="address",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="munigeo.municipality",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="search_column_en",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="search_column_fi",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="search_column_sv",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="syllables_fi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="administrativedivision",
            name="extra",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="administrativedivision",
            name="search_column_en",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="administrativedivision",
            name="search_column_fi",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="administrativedivision",
            name="search_column_sv",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="administrativedivision",
            name="units",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="code",
            field=models.CharField(default="", max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="modified_at",
            field=models.DateTimeField(
                help_text="Time when the information was last changed"
            ),
        ),
        migrations.AlterField(
            model_name="administrativedivision",
            name="origin_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_fi"], name="munigeo_add_search__efb82b_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_sv"], name="munigeo_add_search__2418cb_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_en"], name="munigeo_add_search__c95720_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="administrativedivision",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_fi"], name="munigeo_adm_search__ce886a_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="administrativedivision",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_sv"], name="munigeo_adm_search__f435c7_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="administrativedivision",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_en"], name="munigeo_adm_search__f7bab1_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="administrativedivision",
            index=models.Index(
                fields=["tree_id", "lft"], name="munigeo_administrativedivi8660"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="postal_code_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="munigeo.postalcodearea",
            ),
        ),
    ]
