# Generated by Django 4.0.4 on 2022-05-11 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("munigeo", "0010_add_postalcodearea"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="municipality",
            field=models.ForeignKey(
                default="helsinki",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="munigeo.municipality",
            ),
            preserve_default=False,
        ),
    ]
