# Generated by Django 4.0.7 on 2022-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munigeo', '0013_add_naturalsort_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='origin_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
