# Generated by Django 4.1.13 on 2024-05-06 06:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("munigeo", "0014_increase_origin_id_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="syllables_fi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16), default=list, size=None
            ),
        ),
    ]
