# Generated by Django 4.2.7 on 2023-12-12 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("munigeo", "0014_increase_origin_id_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrativedivision",
            name="service_point_id",
        ),
    ]
