# Generated by Django 4.1.13 on 2024-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("munigeo", "0015_address_syllables_fi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="modified_at",
            field=models.DateTimeField(
                help_text="Time when the information was last changed"
            ),
        ),
    ]
