# Generated by Django 4.1.13 on 2024-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("munigeo", "0016_address_modified_at_remove_auto_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="modified_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Time when the information was last changed"
            ),
        ),
    ]
