# Generated by Django 5.2.6 on 2025-09-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munigeo', '0016_address_modified_at_remove_auto_now'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='administrativedivision',
            index=models.Index(fields=['tree_id', 'lft'], name='munigeo_administrativedivi8660'),
        ),
    ]
