# Generated by Django 5.2.13 on 2026-04-16 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("munigeo", "0017_administrativedivision_munigeo_administrativedivi8660"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="street",
            unique_together={
                ("municipality", "name"),
                ("municipality", "name_en"),
                ("municipality", "name_fi"),
                ("municipality", "name_sv"),
            },
        ),
    ]
