# Generated by Django 4.2.30 on 2026-04-17 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("munigeo", "0018_alter_street_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="street",
            unique_together={
                ("municipality", "name_fi"),
                ("municipality", "name_en"),
                ("municipality", "name_sv"),
            },
        ),
        migrations.RemoveField(
            model_name="address",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="administrativedivision",
            name="name",
        ),
        migrations.RemoveField(
            model_name="municipality",
            name="name",
        ),
        migrations.RemoveField(
            model_name="postalcodearea",
            name="name",
        ),
        migrations.RemoveField(
            model_name="street",
            name="name",
        ),
    ]
